require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - bin/*
    - config/**/*
    - coverage/**/*
    - db/**/*
    - doc/**/*
    - log/**/*
    - public/**/*
    - script/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Exclude:
    - app/api/**/*
    - app/controllers/**/*
    - app/helpers/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing

Lint/RescueException:
  Exclude:
    - 'lib/tasks/*.rake'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - '**/*.rake'
Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'
Metrics/MethodLength:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  Enabled: false

Rails:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
RSpec/DescribedClass:
  EnforcedStyle: explicit
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectInHook:
  Exclude:
    - 'spec/features/**/*'
RSpec/HookArgument:
  EnforcedStyle: each
RSpec/LetSetup:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ImplicitExpect:
  EnforcedStyle: is_expected
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/NestedGroups:
  Enabled: false
RSpec/NotToNot:
  EnforcedStyle: not_to
RSpec/VerifiedDoubles:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template
Style/Lambda:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/GuardClause:
  Severity: warning
